// <auto-generated />
using System;
using DaireYonetimAPI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DaireYonetimAPI.DataAccess.Migrations
{
    [DbContext(typeof(DaireDbContext))]
    [Migration("20230807133422_mig_updatadatabase")]
    partial class mig_updatadatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DaireYönetimAPI.Entity.Bakiye", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("BorcBakiye")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DaireId")
                        .HasColumnType("int");

                    b.Property<int>("DaireNo")
                        .HasColumnType("int");

                    b.Property<decimal>("Faiz")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OdemeTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SonOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ToplamBorc")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("Bakiyes");
                });

            modelBuilder.Entity("DaireYönetimAPI.Entity.Daire", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<int?>("BakiyeId")
                        .HasColumnType("int");

                    b.Property<decimal>("BorcBakiye")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SonOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("aidatödemedurumu")
                        .HasColumnType("bit");

                    b.Property<string>("daireaidat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("daireeposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("daireisim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dairenumber")
                        .HasColumnType("int");

                    b.Property<string>("geçerliliktarihi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Daires");
                });

            modelBuilder.Entity("DaireYönetimAPI.Entity.Daire", b =>
                {
                    b.HasOne("DaireYönetimAPI.Entity.Bakiye", "Bakiye")
                        .WithOne("Daire")
                        .HasForeignKey("DaireYönetimAPI.Entity.Daire", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bakiye");
                });

            modelBuilder.Entity("DaireYönetimAPI.Entity.Bakiye", b =>
                {
                    b.Navigation("Daire");
                });
#pragma warning restore 612, 618
        }
    }
}
